name: build

on:
  push:
    branches:
      - sdn6-full-example
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: with jdk ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean verify
